fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: '%env(resolve:MAILER_USER)%'
    sender_name: '%env(resolve:MAILER_USER)%'
  group:
    group_class:   FOS\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager